a-r-r-o-w/finetrainers

- README.md
- README_zh.md
- training/cogvideox_image_to_video_lora.py
- training/dataset.py
- training/prepare_dataset.py
> Improve dataset preparation support + multiresolution prep

- training/cogvideox_image_to_video_lora.py
- training/cogvideox_text_to_video_lora.py
- training/cogvideox_text_to_video_sft.py
@Nojahhh Would you mind giving this a review? You've already fixed the dataset side of things with lambda pickling error, and this PR replaces the inline collate_fn with a class instance as per your PR #32 in the remaining scripts
> Windows support for T2V scripts

- training/cogvideox_text_to_video_sft.py
wandb tracker in scheduling problems during the training initiation and training stages
Login is not performed as expected during startup
> wandb tracker in scheduling problems during the training initiation and training stages

- training/cogvideox_image_to_video_lora.py
- training/cogvideox_text_to_video_lora.py
- training/cogvideox_text_to_video_sft.py
is some error
```
[rank1]: Traceback (most recent call last):                                                                             [rank1]:   File "/mnt/ceph/develop/jiawei/cogvideox-distillation/training/cogvideox_image_to_video_lora.py", line 1005, in <module>                                                                                                             [rank1]:     main(args)                                                                                                 [rank1]:   File "/mnt/ceph/develop/jiawei/cogvideox-distillation/training/cogvideox_image_to_video_lora.py", line 884, in main                                                                                                                  [rank1]:     "gradient_norm_before_clip": …
```
> Unbound fix

- finetrainers/trainer.py
cc @sayakpaul 
Merging by bypassing restrictions because this was done incorrectly inside the loop than outside. It was not caught because I was only testing with 2 validation prompts on 2 GPU devices when this change was added. Getting some reports from people that it's broken
> fix validation bug

- Makefile
- README.md
- accelerate_configs/deepspeed.yaml
- accelerate_configs/uncompiled_2.yaml
- finetrainers/args.py
- finetrainers/state.py
- finetrainers/trainer.py
- finetrainers/utils/checkpointing.py
- finetrainers/utils/optimizer_utils.py
- finetrainers/utils/torch_utils.py
- train.py
There are additional things that I have clubbed in this PR. LMK your thoughts. Some comments in-line. 
To test:
<details>
<summary>command</summary>
```bash
export NCCL_P2P_DISABLE=1
export TORCH_NCCL_ENABLE_MONITORING=0
export FINETRAINERS_LOG_LEVEL=DEBUG
GPU_IDS="0,1"
DATA_ROOT="/home/sayak/finetrainers/video-dataset-disney"
CAPTION_COLUMN="prompt.txt"
VIDEO_COLUMN="videos.txt"
OUTPUT_DIR="/raid/.cache/huggingface/sayak/ltx-video/ltxv_disney"
model_cmd="--model_name ltx_video \
--pretrained_model_name_or_path Lightricks/LTX-Video"
dataset_cmd="--data_root $DATA_ROOT \
--video_column $VIDEO_COLUMN \
--caption_column $CAPTION_COLUMN \
--id_token BW_STYLE \
--video_resolution_buckets 49x512x768 \
--caption_dropout_p 0.05"
dataloader_cmd="--dataloader_num_workers 4" …
```
> [feat] support DeepSpeed.

- README.md
- finetrainers/args.py
- finetrainers/trainer.py
- finetrainers/utils/optimizer_utils.py
Fixes #137. 
Run: https://wandb.ai/sayakpaul/finetrainers-ltxv/runs/7kk3xhkh
> [optimization] support 8bit optims from bistandbytes

- .github/workflows/pr_tests.yml
Follow-up would be a basic test suite (I hope you're okay with that, but if not, I will understand).
> [CI] add a workflow to do quality checks.

- README.md
- docs/training/cogvideox.md
- docs/training/hunyuan_video.md
- docs/training/ltx_video.md
* Simply the support matrix table.
* Move the supported checkpoints to the respective model docs. Currently, this only applies to CogVideoX as that is the one with multiple checkpoints available.
> simplify docs part ii

- README.md
- docs/training/ltx_video.md
The major change is that we using logit_normal weighting as described in the paper. We did not know this detail beforehand when LTXV support was added leading to suboptimal loss.
> Better defaults for LTXV

- finetrainers/dataset.py
- finetrainers/trainer.py
Fixes https://github.com/a-r-r-o-w/finetrainers/issues/200
Tested on current three supported models:
| Model      | WandB Run Page                        |
|------------|---------------------------------------|
| LTX    | [Run Page](https://wandb.ai/sayakpaul/finetrainers-ltxv/runs/vrmvp0or) |
| Cog    | [Run Page](https://wandb.ai/sayakpaul/finetrainers-cogvideox/runs/v76utg0p) |
| Model C    | [Run Page](https://wandb.ai/sayakpaul/finetrainers-hunyuan-video/runs/tv6kf38a) |
<details>
<summary>LTX</summary>
```bash
export WANDB_MODE="offline"
export NCCL_P2P_DISABLE=1
export TORCH_NCCL_ENABLE_MONITORING=0
export FINETRAINERS_LOG_LEVEL=DEBUG
GPU_IDS="0,1"
DATA_ROOT="video-dataset-disney"
CAPTION_COLUMN="prompt.txt"
VIDEO_COLUMN="videos.txt"
OUTPUT_DIR="ltxv_disney"
ID_TOKEN="BW_STYLE" …
```
> [core] Fix loading of precomputed conditions and latents

- finetrainers/trainer.py
Unrelated change in introduced in #184, so we can do a separate PR to unblock its introduction.
Test run: https://wandb.ai/aryanvs/finetrainers-ltxv/runs/quwm5a1r
> Epoch loss

- tests/scripts/dummy_cogvideox_lora.sh
- tests/scripts/dummy_hunyuanvideo_lora.sh
- tests/scripts/dummy_ltx_video_lora.sh
- tests/test_dataset.py
- tests/test_model_runs_minimally_lora.sh
Have run and can confirm it's working as expected. Since this script will be used quite (or so I think) heavily, I would appreciate if you could run it, too.
> Shell script to minimally test supported models on a real dataset

- .github/workflows/pr_tests.yml
We use this version in `diffusers`. Will unblock https://github.com/a-r-r-o-w/finetrainers/actions/runs/12701999964/workflow?pr=202.
> Update pr_tests.yml to update ruff version

- finetrainers/utils/checkpointing.py
Currently, the checkpoint dirs scanned only have the folder names not full paths. So, `delete_files` won't delete anything if `output_dir` is any non-empty path. Just a very simple fix to make checkpointing_limit work robustly.
> Fix the checkpoint dir bug in `get_intermediate_ckpt_path`

- finetrainers/args.py
`python train.py --list_models`
> Helpful messages

- training/mochi-1/text_to_video_lora.py
- training/mochi-1/utils.py
> Fix: Utils error in mochi finetuning script

- finetrainers/args.py
- finetrainers/trainer.py
When `training_type == "full-finetune"`, I think we should reset the default values of LoRA related args like `lora_alpha`, `rank`, etc. Otherwise, the logged args in the tracker might be confusing for the users. 
No need to explain if this is not right, I will close the PR. Thought of directly opening a PR as it was easier and not time-consuming at all.
Example overview: https://wandb.ai/sayakpaul/finetrainers-cog/runs/t1c5jcj3/overview.
> [Chore] reset unnecessary args

- finetrainers/trainer.py
Currently, we first wait for all processes to complete before saving the final state dict (which happens under the main process). We then proceed towards distributed validation. The nuance of this is that distributed validation can start even before the state dict serialization is complete. 
Below is a snippet of the problem:
<details>
<summary>Unfold</summary>
```bash
ERROR:finetrainers:Traceback (most recent call last):
File "/fsx/sayak/finetrainers/train.py", line 35, in main
trainer.train()
File "/fsx/sayak/finetrainers/finetrainers/trainer.py", line 844, in train
self.validate(step=global_step, final_validation=True)
File "/fsx/sayak/finetrainers/finetrainers/trainer.py", line 873, in validate
pipeline = self._get_and_prepare_pipeline_for_validation(final_validation=final_validation) …
```
> [core] fix pipeline loading by waiting till `transformer` is saved.

- README.md
- training/train_image_to_video_sft.sh
the example dataset id provided in the README ([Wild-Heart/Disney-VideoGeneration-Dataset](https://huggingface.co/datasets/Wild-Heart/Disney-VideoGeneration-Dataset)) has caption path as `prompt.txt` (see [captions file](https://huggingface.co/datasets/Wild-Heart/Disney-VideoGeneration-Dataset/blob/823c1f015e7ced7fffb8ad44881f792195114386/prompt.txt))  but README and related training scripts uses `prompts.txt`
> fix(typo): captions path in disney dataset

- finetrainers/trainer.py
- finetrainers/utils/hub_utils.py
* Save model cards when requested even when there's no validation prompt.
* Logging of the ID_token in the model card.
* Better tags for model card.
Example: https://huggingface.co/sayakpaul/dummy-ltx
> fix: model card info.

- finetrainers/trainer.py
- finetrainers/utils/hub_utils.py
Referencing: https://huggingface.co/docs/accelerate/main/en/concept_guides/deferring_execution
This PR ensures:
We download files first on the main process and then load the cached files afterward i.e., other processes. 
Have run the tests, too. Absolutely okay if you don't want it.
> [core] Ensure loading mp first

- examples/hunyuan_video/convert_diffusers_lora_to_original.py
Thanks to kijai for finding this, img_attn.proj and img_attn.qkv wasn't working with wrapper (which is based on original code) but replacing with _proj and _qkv works for both
> updating weight names to match original instead of comfyui

- finetrainers/trainer.py
Previously, when `num_validation_samples == 0` then `save_model_card` was called even if `self.args.push_to_hub` or `final_validation` was `False`.
> calling save_model_card correctly

- examples/training/sft/wan/3dgs_dissolve/train.sh
- examples/training/sft/wan/3dgs_dissolve/training.json
- examples/training/sft/wan/3dgs_dissolve/validation.json
From a small set of experiments (~10), I've found it hard to train in new concepts to the 1.3B model. It ultimately leads to model collapsing and performing bad with the lora. This is my best results so far:
https://github.com/user-attachments/assets/66d74fcb-999d-4014-847a-ef7abd74f0c7
Still not going for training the 14B variants because we need to make training significantly faster. The following are on my mind to support quickly:
- PTD experimental context parallel
- Flash Attention natively in diffusers (WIP)
> Add 3DGS dataset example for Wan

- examples/training/sft/cogview4/raider_white_tarot/train.sh
- examples/training/sft/cogview4/raider_white_tarot/training.json
- examples/training/sft/cogview4/raider_white_tarot/validation.json
- finetrainers/config.py
- finetrainers/data/dataset.py
- finetrainers/functional/image.py
- finetrainers/models/cogview4/__init__.py
- finetrainers/models/cogview4/base_specification.py
- finetrainers/processors/__init__.py
- finetrainers/processors/glm.py
- finetrainers/trainer/sft_trainer/trainer.py
- tests/models/cogview4/base_specification.py
- tests/trainer/test_sft_trainer.py
Wandb logs: https://wandb.ai/aryanvs/finetrainers-cogview4
Checkpoints:
- https://huggingface.co/finetrainers/CogView4-6B-rider-waite-tarot-v0
- https://huggingface.co/finetrainers/CogView4-6B-rider-waite-tarot-v0-shifted-sigmas
> CogView4 ModelSpec

- docs/dataset/README.md
- examples/training/sft/cogvideox/crush_smol_lora/train.sh
- examples/training/sft/cogview4/raider_white_tarot/train.sh
- examples/training/sft/hunyuan_video/modal_labs_dissolve/train.sh
- examples/training/sft/ltx_video/crush_smol_lora/train.sh
- examples/training/sft/ltx_video/crush_smol_lora/train_multires.sh
- examples/training/sft/wan/3dgs_dissolve/train.sh
- examples/training/sft/wan/crush_smol_lora/train.sh
- finetrainers/args.py
- finetrainers/data/__init__.py
- finetrainers/data/dataset.py
- finetrainers/data/precomputation.py
- finetrainers/trainer/sft_trainer/trainer.py
- finetrainers/utils/__init__.py
- finetrainers/utils/diffusion.py
- tests/data/test_dataset.py
- tests/data/test_precomputation.py
- tests/data/utils.py
- tests/trainer/test_sft_trainer.py
Fixes #296 and #295.
Adds a `--enable_precomputation` flag. It is disable by default to that one can train normally without saving/loading from disk.
Adds some basic sanity-checking tests.
TODO:
cc @tau-yihouxiang @dorpxam
> Remove forceful precomputation behaviour; Improvements to data loading

- finetrainers/models/cogvideox/base_specification.py
CogVideoX-2B does not have this config attribute and will raise an error with previous check
> Fix CogVideoX config error for invert_scale_latents

- finetrainers/patches/__init__.py
- finetrainers/patches/models/ltx_video/patch.py
- finetrainers/patches/models/wan/patch.py
- finetrainers/trainer/sft_trainer/trainer.py
- tests/README.md
- tests/models/cogvideox/base_specification.py
- tests/models/cogview4/base_specification.py
- tests/models/hunyuan_video/base_specification.py
- tests/models/ltx_video/base_specification.py
- tests/models/wan/base_specification.py
- tests/trainer/test_sft_trainer.py
Fixes #312.
@dorpxam Could you give this branch a try with what you were trying in #312?
Important to note that:
- this is "fake" fp8 training, i.e. it's not quantization-aware training and might produce worse results than bf16/fp32 training
- it won't work on > 1 GPU training because of unimplemented cuda collective operations for `torch.float8*` types
> Fix Layerwise Casting 

- finetrainers/patches/__init__.py
#316 fixed a bug for FP8 layerwise casting training. However, the fix breaks bf16 training. This PR enables the patch only if using FP8 casting
> Patch WanTimeTextImageEmbedding forward only with fp8

- finetrainers/args.py
- finetrainers/trainer/sft_trainer/trainer.py
Fixes https://github.com/a-r-r-o-w/finetrainers/issues/315#issuecomment-2715432823
Testing only with CogView4. It should have a similar effect on all other models due to same code paths.
-----
On multi-GPU, there should be no change based on the changes made.
-----
On single-GPU using no memory optimization flags (except the must-use defaults like `--gradient_checkpointing`:
| Phase                          | Value                  | Before  | This PR  |
|--------------------------------|------------------------|---------|----------|
| Memory before training start   | memory_allocated      | 11.973  | 11.973   |
|                                | memory_reserved       | 11.98   | 11.98    |
|                                | max_memory_allocated  | 11.973  | 11.973   |
| …
> Lower memory requirements on single GPU

- finetrainers/trainer/sft_trainer/__init__.py
This is a fix for #335
In order for the content of `/finetrainers/trainer/sft_trainer/` to be copied during `pip install`, I believe it is necessary to put a `__init__.py` inside the directory
> add __init__.py to sft_trainer/ to fix #335

- finetrainers/args.py
- finetrainers/data/dataset.py
- finetrainers/utils/import_utils.py
Fixes #329
20x faster data loading with https://github.com/huggingface/datasets/releases/tag/3.4.0 🥳 
cc @jbilcke-hf LMK if this works for you. I have not tested with a training run, but verified that the output shapes and values between the versions match
> Add version guard for datasets 3.4.0; Fix argument documentation

- README.md
- finetrainers/args.py
- finetrainers/trainer/sft_trainer/trainer.py
- finetrainers/utils/__init__.py
- finetrainers/utils/_common.py
- finetrainers/utils/torch.py
- tests/trainer/test_sft_trainer.py
Adds support for regional compilation on transformer blocks.
Training speedup with `torch.compile` can be enabled by settings `--compile_modules transformer` when launching training.
Accelerate hasn't been tested yet but most likely should work. As it hasn't been tested, unit tests are not yet added either.
> Pytorch regional compilation

- finetrainers/functional/image.py
- finetrainers/functional/video.py
When I was finetuning a flux-dev model with my custom dataset, I got the following error:
```
Calculated padded input size per channel: (2 x 321). Kernel size: (3 x 3). Kernel size can't be greater than the actual input size
```
It was confusing, and it turned out that the image in my dataset was smaller than the crop size, which eventually led to the kernel error.
I suggest we raise an exception when the input image/video is of the wrong size.
Moreover, I think we may add an option to keep only those images whose sizes are no smaller than the crop size and drop the others. (if needed, I can do that)
> [Fix] Raise ValueError proactively before some confusing errors occur due to wrong input image size

- finetrainers/trainer/sft_trainer/trainer.py
Fixes #352.
The mistake was probably made last minute due to some undo's during the major refactor for accelerate compatibility - #339 - because the test suite ran to completion.
> Fix #352: FSDP2 argument typo

- finetrainers/data/precomputation.py
Fixes the original issue as mentioned in #348.
The problem comes from the older precomputed files not getting cleaned up as is expected from the code behaviour. It is due to a simple mismatch of how the paths were configured after the last round of refactoring
> Fix precomputation-related file deletion when starting new runs

- finetrainers/models/wan/base_specification.py
- finetrainers/models/wan/control_specification.py
Fixes an attribute access bug introduced in #388 that required either:
- updating the diffusers version so that the default value for attributes was set
- updating the existing model config to contain these attributes
> Fix Wan attribute access
